---
# Remove following line 'ansible_python_interpreter=/usr/bin/python3'
# to install MySQL-Python dependencies, using a manually linked Python2.7
- name: Add LAMP host to our inventory.
  add_host: >
    hostname=lamp
    ansible_host={{ lamp.droplet.ip_address }}
    ansible_port=22
    groups=web
    ansible_connection=ssh
    ansible_become=yes
    ansible_become_method=sudo
    ansible_become_user=root
    ansible_private_key_file='~/.ssh/REMOTE'
    ansible_ssh_common_args='-o StrictHostKeyChecking=no'
    allow_world_readable_tmpfiles=True
    ansible_python_interpreter=/usr/bin/python3
  register: new_lamp_host

- name: Add JENKINS host to our inventory.
  add_host: >
    hostname=jenkins
    ansible_host={{ jenkins.droplet.ip_address }}
    ansible_port=22
    groups=web
    ansible_connection=ssh
    ansible_become=yes
    ansible_become_method=sudo
    ansible_become_user=root
    ansible_private_key_file='~/.ssh/REMOTE'
    ansible_ssh_common_args='-o StrictHostKeyChecking=no'
    allow_world_readable_tmpfiles=True
    ansible_python_interpreter=/usr/bin/python3
  register: new_jenkins_host
