---
- include: local_ssh_keys.yml
- include: servers.yml
  when: my_ssh_key is defined
- include: hosts.yml
  when:
    - lamp.droplet is defined
    - jenkins.droplet is defined
- include: remote_ssh_keys.yml
  when:
    - new_lamp_host is defined
    - new_jenkins_host is defined
