---
- name: Destroy LAMP server
  digital_ocean: >
    state=deleted
    command=droplet
    name=lamp
    private_networking=yes
    size_id=512mb
    image_id=ubuntu-16-04-x64
    region_id=nyc1
    ssh_key_ids={{ my_ssh_key.ssh_key.id }}
    api_token={{ do_token }}
    wait=yes
    unique_name=yes
  register: lamp

- name: Destroy JENKINS server
  digital_ocean: >
    state=deleted
    command=droplet
    name=jenkins
    private_networking=yes
    size_id=2gb
    image_id=ubuntu-16-04-x64
    region_id=nyc1
    ssh_key_ids={{ my_ssh_key.ssh_key.id }}
    api_token={{ do_token }}
    wait=yes
    unique_name=yes
  register: jenkins