---
- name: Get software for apt repository management.
  apt: "name={{ item }} state=present"
  with_items:
    - python-apt
    - python-pycurl

- name: Disable the firewall (since this is for local dev only).
  service: name=ufw state=stopped

- name: install python mysql bindings
  apt:
    name: python2.7
    state: present
    update_cache: yes

- name: create python symlink
  file:
    src: /usr/bin/python2.7
    dest: /usr/bin/python
    owner: root
    group: root
    state: link